export const data = [
    {
      question: "Which programming language is used to style web pages?",
      option1: "HTML",
      option2: "CSS",
      option3: "JavaScript",
      option4: "Python",
      ans: 2,
    },
    {
      question: "What does HTTP stand for?",
      option1: "HyperText Transfer Protocol",
      option2: "Hyperlink Transfer Protocol",
      option3: "Hyper Terminal Transfer Program",
      option4: "Hypertext Transfer Process",
      ans: 1,
    },
    {
      question: "Which of the following is a JavaScript library?",
      option1: "Laravel",
      option2: "React",
      option3: "Django",
      option4: "Flask",
      ans: 2,
    },
    {
      question: "What is the full form of RAM?",
      option1: "Random Access Memory",
      option2: "Read Access Memory",
      option3: "Run Access Memory",
      option4: "Rapid Access Memory",
      ans: 1,
    },
    {
      question: "Which company developed the Android operating system?",
      option1: "Apple",
      option2: "Microsoft",
      option3: "Google",
      option4: "IBM",
      ans: 3,
    },
    {
      question: "Which HTML element is used to define a hyperlink?",
      option1: "<link>",
      option2: "<a>",
      option3: "<href>",
      option4: "<anchor>",
      ans: 2,
    },
    {
      question: "Which of the following is used to structure a webpage?",
      option1: "CSS",
      option2: "HTML",
      option3: "JavaScript",
      option4: "Python",
      ans: 2,
    },
    {
      question: "What does SQL stand for?",
      option1: "Structured Query Language",
      option2: "Simple Query Language",
      option3: "Sequential Query Language",
      option4: "Standard Query Language",
      ans: 1,
    },
    {
      question: "Which of the following is a version control system?",
      option1: "Git",
      option2: "Node.js",
      option3: "NPM",
      option4: "Webpack",
      ans: 1,
    },
    {
      question: "In which language is React.js written?",
      option1: "C++",
      option2: "Python",
      option3: "JavaScript",
      option4: "Ruby",
      ans: 3,
    },
];
